name: Deploy GitHub Pages

on:
  push:
    paths:
      - 'sito/**' # Triggers only when files in the 'sito' directory are changed
      - '.github/workflows/deploy.yml' # Optional: to update workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sito # Folder to deploy
